# Generated by Django 4.2.7 on 2024-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
