# Generated by Django 4.2.7 on 2024-01-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='counrty',
            new_name='country',
        ),
    ]
