# Generated by Django 4.2.7 on 2024-01-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_borrowbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='book_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
