# Generated by Django 4.2.7 on 2024-01-04 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_book_price'),
        ('user', '0004_alter_borrowbook_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='balance_A_B_Book',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('star', models.CharField(choices=[('1', '*'), ('2', '*'), ('3', '*'), ('4', '*'), ('5', '*')], max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='books.book')),
            ],
        ),
    ]
