# Generated by Django 4.2.7 on 2024-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_borrowbook_balance_a_b_book_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.CharField(blank=True, choices=[('1', '*'), ('2', '*'), ('3', '*'), ('4', '*'), ('5', '*')], max_length=50, null=True),
        ),
    ]
