# Generated by Django 4.2.7 on 2024-01-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_review_body_alter_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.CharField(blank=True, choices=[('*', '*'), ('**', '*'), ('***', '*'), ('****', '*'), ('*****', '*')], max_length=50, null=True),
        ),
    ]
