# Generated by Django 4.2.7 on 2024-01-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_book_price'),
        ('user', '0008_borrowbook_book_alter_borrowbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='book', to='books.book'),
        ),
    ]
