# Generated by Django 4.2.7 on 2024-01-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_borrowbook_book_borrowbook_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='book_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
