# Generated by Django 4.2.7 on 2024-01-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_borrowbook_book_borrowbook_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
